# Generated by Django 4.0.2 on 2022-02-16 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoApp', '0002_booking_city_restaurant_seat_seatbookingmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_price', models.FloatField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zomatoApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_name', models.CharField(max_length=100)),
                ('payment_charges', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('convinience_fee', models.FloatField(default=0)),
                ('delivery_fee', models.FloatField(default=0)),
                ('discount_val', models.FloatField(default=0)),
                ('order_price', models.FloatField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zomatoApp.cart')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zomatoApp.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zomatoApp.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zomatoApp.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zomatoApp.item')),
            ],
        ),
    ]
