# Generated by Django 4.0.2 on 2022-02-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoApp', '0003_cart_payment_order_item_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='active',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='active',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='status',
        ),
        migrations.AddField(
            model_name='seat',
            name='booking_status',
            field=models.IntegerField(default=0),
        ),
    ]
