# Generated by Django 4.0.2 on 2022-02-16 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoApp', '0004_rename_active_cart_status_rename_active_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zomatoApp.user'),
        ),
    ]
