# Generated by Django 4.0.2 on 2022-02-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoApp', '0007_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='booking_status',
        ),
    ]
